blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/WarehouseFinds/PSRedfish/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issues
    url: https://github.com/WarehouseFinds/PSRedfish/security/advisories/new
    about: Report security vulnerabilities privately
